### ISSUE TITLE
Design details

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/contribute.dev#1]
Font headlines: Bodoni 72, Bold
Font text: Avenir Next, Regular
Text color: #404040
Purple highlights: #9A88D5

[Icons.zip](https://github.com/gitpod-io/contribute.dev/files/3354957/Icons.zip)
[logos.zip](https://github.com/gitpod-io/contribute.dev/files/3354965/logos.zip)

Let me know if you need anything else :)

**Comment by jankeromnes** [comment]
New mock-up: (thanks @ChristinFrohne! 💯)

![Mockup](https://user-images.githubusercontent.com/599268/61216416-99e75980-a70d-11e9-86f5-55591a310c7e.png)

**Comment by meysholdt** [comment]
I like the lightness and brightness of the new design as well as the similarity to the gitpod-workspace-list.

**Comment by ChristinFrohne** [comment]
Cool! I'm happy that you like it. 
Here is a link where you can add some feedback. I already implemented most of @jankeromnes  Feedback 
https://xd.adobe.com/view/3aa3599c-cbd6-4df6-53e3-4120a20f8f47-4c92/

@nisarhassan12 I found a way to provide you a developer view on the mockup, so you don't need to type the texts anymore! https://xd.adobe.com/spec/d2c802e6-a24b-470b-67ca-8a5b6e2ac5d1-a4f9/grid
