### ISSUE TITLE
N

### ISSUE THREAD

**Issue by schmatthy** [gitpod-io/contribute.dev#100]
### Does your project have basic newcomer onboarding docs? (e.g. CONTRIBUTING.md, good-first-issues...)

**Comment by nisarhassan12** [comment]
Thanks, @schmatthy for the issue it is missing the projects repo URL, please provide that

Would you please answer the following:

- Is novous.com Open Source? 
- why it is exciting and interesting to contribute to?

**Comment by nisarhassan12** [comment]
Closing this due to the lack of information and also novous.com looks like an agency's website rather than an OSS which is exciting to contribute to.
