### ISSUE TITLE
Please add https://github.com/robotology/icub-gazebo-grasping-sandbox

### ISSUE THREAD

**Issue by pattacini** [gitpod-io/contribute.dev#109]
The [iCub Gazebo Grasping Sandbox][1] is a project that we have very recently realized at [iCubTech@IIT][2] with the aim to support learning paths in robotics, specifically for what concerns the topic of simulated visuo-manipulation tasks with the iCub humanoid.

In a broader sense, the project turns out to be peculiar in that:
- To our knowledge, it's the only "sandbox" in robotics that makes heavy use of Gitpod.
- It is fully self-contained as it closes the loop with its GitHub repository for what pertains to building the Docker images through a GitHub action that serves to publish to the GitHub Container Registry.
- It does very well summarize our efforts for providing a cloud platform based on Gitpod to be used in schools and in crash courses. This approach is explained in the following posts:
    - https://education.github.community/t/the-benefits-of-integrating-docker-and-cloud-ides-in-the-github-classroom-workflow/40724
    - https://spectrum.chat/icub/technicalities/yarp-enabled-gitpod-workspaces-available~73ab5ee9-830e-4b7f-9e99-195295bb5e34
    - https://spectrum.chat/icub/technicalities/get-yarp-enabled-workspaces-on-the-cloud-with-a-single-click~53ba1286-4d46-4402-94f5-4aa321f03fb5

### Is your project's development setup fully automated? How to use it?
**Yes**
In the main README file, there is a session that shows how with one click and a few bash commands you can run the full simulation as per the animation below:

![animation][3]

Also, we made available a [walkthrough][4] with a video tutorial showing the basic Gitpod functionalities. 

### Why is your project interesting/exciting to contribute to?
The sandbox represents an interesting work that showcases how with relatively simple components we can code grasping in a simulated environment using 3D vision. The code is documented and is meant to provide a baseline to build more complex behaviors on top.

### Does your project have an active community?
**Yes**
The community gravitating around the [iCub project][5] operates worldwide leveraging on the open-source.
Most of the software we develop is published at https://github.com/robotology.

### Does your project have basic newcomer onboarding docs? (e.g. CONTRIBUTING.md, good-first-issues...)
**Yes**
Contributing guidelines are explicitly available from the repository. 

[1]: https://github.com/robotology/icub-gazebo-grasping-sandbox
[2]: https://iit.it/research/facilities/icub-tech
[3]: https://raw.githubusercontent.com/robotology/icub-gazebo-grasping-sandbox/master/assets/showcase.gif
[4]: https://robotology.github.io/icub-gazebo-grasping-sandbox
[5]: https://icub.iit.it/

**Comment by nisarhassan12** [comment]
Thanks for the issue. I'll make a Pr for this.

**Comment by nisarhassan12** [comment]
@pattacini Can you provide me with the logo of the project?

**Comment by pattacini** [comment]
Thanks a lot @nisarhassan12 👍🏻 

Here's the logo:

![head-solid](https://user-images.githubusercontent.com/3738070/94543608-91b00700-024a-11eb-8c28-edfad5933711.png)
