### ISSUE TITLE
Please add https://gitlab.com/taskord/taskord

### ISSUE THREAD

**Issue by bigint** [gitpod-io/contribute.dev#112]
### Is your project's development setup fully automated? How to use it?

Yes

![image](https://user-images.githubusercontent.com/69431456/95022069-7b62da80-0692-11eb-913e-e1e0f613ea12.png)

### Why is your project interesting/exciting to contribute to?

Taskord is free open source social media for tasks! where users can post public and private todos, ask questions, and launch products. Taskord helps you to get things done together with the members of the community.

### Does your project have an active community?

Yes Taskord has around 80 users in alpha stage, we will be on ProductHunt soon!

https://taskord.com

### Does your project have basic newcomer onboarding docs? (e.g. CONTRIBUTING.md, good-first-issues...)

Yes we have CONTRIBUTING.md, INTALLATION.md etc

And there is public product roadmap here https://share.clickup.com/b/h/357rd-718/6f57394b40f19f8

/cc @jankeromnes

**Comment by nisarhassan12** [comment]
Thanks. for the issue this is gonna be the first Gitlab project that we're about to add to the list.
We would have to tailor the `add project` script to support Gitlab and also some changes to the Project List are required. Once we're done with those. I'll make a Pr for adding this to the list.

**Comment by nisarhassan12** [comment]
@bigint I have made a PR for this. Would be great if you can help me with this: https://github.com/gitpod-io/contribute.dev/pull/118#issuecomment-714619571
