### ISSUE TITLE
Add more projects to the list

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/contribute.dev#13]
We'd like to add more projects with frictionless contributions to the list. In this issue, I'll attempt to list projects that have an automated setup, so that we can review their developer experience and assess whether it makes sense to add them or not.

| Project | Automated setup working? | Contributor friendly? | Init duration? | Badge location? | Should be added? |
| --- | :---: | :---: | :---: | :---: | :---: |
| [FreeCodeCamp ![stars](https://img.shields.io/github/stars/freeCodeCamp/freeCodeCamp?style=social)](https://github.com/freeCodeCamp/freeCodeCamp) | ✅ |  ✅ | ~minutes | CONTRIB.md | ✅ |
| [The Algorithms - Python ![stars](https://img.shields.io/github/stars/TheAlgorithms/Python?style=social)](https://github.com/TheAlgorithms/Python) | ❌ <sup>2</sup> | ✅ |  | README.md | ✅ |
| [Ant Design ![stars](https://img.shields.io/github/stars/ant-design/ant-design?style=social)](https://github.com/ant-design/ant-design/) | ✅ |  |  |  | ✅ |
| [Gatsby ![stars](https://img.shields.io/github/stars/gatsbyjs/gatsby?style=social)](https://github.com/gatsbyjs/gatsby) | ✅ |  | [9 minutes](https://github.com/gatsbyjs/gatsby/pull/17718) |  | ❌ |
| [Ghost ![stars](https://img.shields.io/github/stars/TryGhost/Ghost?style=social)](https://github.com/TryGhost/Ghost) |  |  |  |  |  |
| [Algorithm Visualizer ![stars](https://img.shields.io/github/stars/algorithm-visualizer/algorithm-visualizer?style=social)](https://github.com/algorithm-visualizer/algorithm-visualizer) | ✅ | ✅ |  | CONTRIB.md | ✅ |
| [Carbon ![stars](https://img.shields.io/github/stars/dawnlabs/carbon?style=social)](https://github.com/dawnlabs/carbon) | ✅ | ✅ |  | CONTRIB.md | ✅ |
| [Ant Design Pro ![stars](https://img.shields.io/github/stars/ant-design/ant-design-pro?style=social)](https://github.com/ant-design/ant-design-pro) |  |  |  |  |  |
| [jsPDF ![stars](https://img.shields.io/github/stars/MrRio/jsPDF?style=social)](https://github.com/MrRio/jsPDF) | ✅ |  |  |  | ✅ |
| [Tesseract.js ![stars](https://img.shields.io/github/stars/naptha/tesseract.js?style=social)](https://github.com/naptha/tesseract.js) | ✅ | ✅ |  | README.md | ✅ |
| [RipGrep ![stars](https://img.shields.io/github/stars/BurntSushi/ripgrep?style=social)](https://github.com/BurntSushi/ripgrep) |  |  |  | ✖️ |  |
| [Servo ![stars](https://img.shields.io/github/stars/servo/servo?style=social)](https://github.com/servo/servo) |  |  |  | ✖️ |  |
| [LearnGitBranching ![stars](https://img.shields.io/github/stars/pcottle/learnGitBranching?style=social)](https://github.com/pcottle/learnGitBranching) |  |  |  |  |  |
| [Koel ![stars](https://img.shields.io/github/stars/phanan/koel?style=social)](https://github.com/phanan/koel) | ✅ | ✅ | ~minutes | README.md | ✅ |
| [Dev.to ![stars](https://img.shields.io/github/stars/thepracticaldev/dev.to?style=social)](https://github.com/thepracticaldev/dev.to) | ✅ <sup>1</sup> | ✅ | ~minutes | README.md | ✅ |
| [Shields ![stars](https://img.shields.io/github/stars/badges/shields?style=social)](https://github.com/badges/shields) | ✅ | ✅ | ~1min | README.md | ✅ |
| [fx ![stars](https://img.shields.io/github/stars/antonmedv/fx?style=social)](https://github.com/antonmedv/fx) |  |  |  | ✖️ |  |
| [Simple Icons ![stars](https://img.shields.io/github/stars/simple-icons/simple-icons?style=social)](https://github.com/simple-icons/simple-icons) | ✅ |  |  | CONTRIB.md |  |
| [Sonoff-Tasmota ![stars](https://img.shields.io/github/stars/arendst/Sonoff-Tasmota?style=social)](https://github.com/arendst/Sonoff-Tasmota) |  |  |  |  |  |
| [Dev Hub ![stars](https://img.shields.io/github/stars/devhubapp/devhub?style=social)](https://github.com/devhubapp/devhub) | ✅ |  |  | CONTRIB.md | ✅ |
| [PeerTube ![stars](https://img.shields.io/github/stars/Chocobozzz/PeerTube?style=social)](https://github.com/Chocobozzz/PeerTube) | ✅ |  |  | CONTRIB.md | ✅ |
| [Trilium ![stars](https://img.shields.io/github/stars/zadam/trilium?style=social)](https://github.com/zadam/trilium) |  |  |  | README.md |  |
| [Theia ![stars](https://img.shields.io/github/stars/eclipse-theia/theia?style=social)](https://github.com/eclipse-theia/theia) | ✅ | ✅ | ~seconds | README.md | ✅ |
| [Nu Shell ![stars](https://img.shields.io/github/stars/nushell/nushell?style=social)](https://github.com/nushell/nushell) | ✅ |  | 6 minutes | README.md |  |
| [Learn JSON Web Tokens ![stars](https://img.shields.io/github/stars/dwyl/learn-json-web-tokens?style=social)](https://github.com/dwyl/learn-json-web-tokens) |  |  |  |  |  |
| [Fusuma ![stars](https://img.shields.io/github/stars/hiroppy/fusuma?style=social)](https://github.com/hiroppy/fusuma) | ✅ | ✅ | ~1min | README.md | ✅ |
| [Learn React App ![stars](https://img.shields.io/github/stars/tyroprogrammer/learn-react-app?style=social)](https://github.com/tyroprogrammer/learn-react-app) |  |  |  | README.md |  |
| [tinyraytracer ![stars](https://img.shields.io/github/stars/ssloy/tinyraytracer?style=social)](https://github.com/ssloy/tinyraytracer) |  |  |  |  |  |
| [tinykaboom ![stars](https://img.shields.io/github/stars/ssloy/tinykaboom?style=social)](https://github.com/ssloy/tinykaboom) |  |  |  |  |  |
| [tinyraycaster ![stars](https://img.shields.io/github/stars/ssloy/tinyraycaster?style=social)](https://github.com/ssloy/tinyraycaster) |  |  |  |  |  |
| [CloudQuery ![stars](https://img.shields.io/github/stars/cloudfetch/cloudquery?style=social)](https://github.com/cloudfetch/cloudquery) |  |  |  | ✖️ |  |
| [ZEIT Now Examples ![stars](https://img.shields.io/github/stars/now-examples/nextgram?style=social)](https://github.com/now-examples/nextgram) |  |  |  |  |  |
| [Statusfy ![stars](https://img.shields.io/github/stars/bazzite/statusfy?style=social)](https://github.com/bazzite/statusfy) | ✅ | ✅ | ~seconds | README.md | ✅ |
| [Vuese ![stars](https://img.shields.io/github/stars/vuese/vuese?style=social)](https://github.com/vuese/vuese) |  |  |  |  |  |
| [Mermrender ![stars](https://img.shields.io/github/stars/Schachte/Mermrender?style=social)](https://github.com/Schachte/Mermrender) |  |  |  |  |  |
| [Home Assistant ![stars](https://img.shields.io/github/stars/home-assistant/home-assistant.io?style=social)](https://github.com/home-assistant/home-assistant.io) |  |  |  |  |  |
| [Ojichat ![stars](https://img.shields.io/github/stars/greymd/ojichat?style=social)](https://github.com/greymd/ojichat) |  |  |  |  |  |
| [Everest ![stars](https://img.shields.io/github/stars/RohitAwate/Everest?style=social)](https://github.com/RohitAwate/Everest) |  |  |  |  |  |
| [NextSimpleStarter ![stars](https://img.shields.io/github/stars/ooade/NextSimpleStarter?style=social)](https://github.com/ooade/NextSimpleStarter) |  |  |  |  |  |
| [Marp CLI ![stars](https://img.shields.io/github/stars/marp-team/marp-cli?style=social)](https://github.com/marp-team/marp-cli) |  |  |  |  |  |
| [GuestBook ![stars](https://img.shields.io/github/stars/st-tu-dresden/guestbook?style=social)](https://github.com/st-tu-dresden/guestbook) |  |  |  |  |  |
| [Sudoku-GUI-Solver](https://github.com/techwithtim/Sudoku-GUI-Solver) |  |  |  | README.md |  |
| [Hangman](https://github.com/techwithtim/Hangman) |  |  |  | README.md |  |
| [Firefox Profiler ![stars](https://img.shields.io/github/stars/firefox-devtools/profiler?style=social)](https://github.com/firefox-devtools/profiler) |  |  |  |  |  |
| [Phoenicis ![stars](https://img.shields.io/github/stars/PhoenicisOrg/phoenicis?style=social)](https://github.com/PhoenicisOrg/phoenicis) |  |  |  |  |  |
| [circuito.io Component Editor](https://github.com/Circuito-io/ComponentEditor) |  |  |  |  |  |
| [learnnextjs-demo ![stars](https://img.shields.io/github/stars/arunoda/learnnextjs-demo?style=social)](https://github.com/arunoda/learnnextjs-demo) |  |  |  |  |  |
| [aoc-2018](https://github.com/rdmueller/aoc-2018) |  |  |  | README.md |  |
| [TasmotaCompiler](https://github.com/benzino77/tasmocompiler) |  |  |  |  |  |
| [Mooniversity](https://github.com/justinmoon/exercises) |  |  |  |  |  |
| [Potigol Online](https://github.com/potigol/gitpod) |  |  |  |  |  |

Notes:
<sup>1</sup> Dev.to setup requires manually creating and copy/pasting Algolia credentials
<sup>2</sup> The Algorithms - Python doesn't have a `.gitpod.yml` (not even in definitely-gp)

**Comment by jankeromnes** [comment]
@akosyakov you've had a look at some of these repositories, right? Could you please briefly share what worked well and what didn't?

**Comment by jankeromnes** [comment]
@nisarhassan12 When you have time, could you please add The Algorithms - Python, Koel and Fusuma? 🙂

**Comment by nisarhassan12** [comment]
Ok. @jankeromnes :slightly_smiling_face:

**Comment by jankeromnes** [comment]
For new projects to be added, please file separate issues from now on.
