### ISSUE TITLE
open-in-gitpod.svg is outdated

### ISSUE THREAD

**Issue by mouse484** [gitpod-io/contribute.dev#147]
The current open-in-gitpod.svg should be orange

![image](https://user-images.githubusercontent.com/38714187/119283214-42a26080-bc77-11eb-91d2-206f7e16386a.png)
![image](https://user-images.githubusercontent.com/38714187/119283219-4635e780-bc77-11eb-8d57-1c48a9dc4482.png)

**Comment by gtsiolis** [comment]
Thanks for noticing @mouse484! I've added https://github.com/gitpod-io/contribute.dev/pull/148 to resolve this. 🏀
