### ISSUE TITLE
Bad email subject in "Become a sponsor" button

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/contribute.dev#16]
<img width="303" alt="Screenshot 2019-08-14 at 17 33 22" src="https://user-images.githubusercontent.com/599268/63034459-b0720380-beb9-11e9-9aa2-332fe31b46b9.png">

Should probably be something like:

> Contribute.dev sponsorship

**Comment by nisarhassan12** [comment]
Thanks! @jankeromnes great catch.
