### ISSUE TITLE
Add RedwoodJS to contribute.dev: https://github.com/redwoodjs/redwood

### ISSUE THREAD

**Issue by phimae** [gitpod-io/contribute.dev#170]
Please add [RedwoodJS](https://github.com/redwoodjs/redwood) to contribute.dev as they have a fully configured [`.gitpod.yml`](https://github.com/redwoodjs/redwood/blob/main/.gitpod.yml)

**Comment by Siddhant-K-code** [comment]
fixed using https://github.com/gitpod-io/contribute.dev/pull/171
