### ISSUE TITLE
Please add https://github.com/SaptarshiSarkar12/Drifty

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [gitpod-io/contribute.dev#193]
Here is the link of an Open-Source project with java as the primary programming language -> https://github.com/SaptarshiSarkar12/Drifty .

**Comment by SaptarshiSarkar12** [comment]
@mbrevoort @mrzarquon @mads-hartmann @gtsiolis Please check if my project is eligible or not.

**Comment by Siddhant-K-code** [comment]
Hey @SaptarshiSarkar12 👋🏼 

Feel free to raise the PR for the same.

**Comment by SaptarshiSarkar12** [comment]
> Hey @SaptarshiSarkar12 👋🏼
> 
> Feel free to raise the PR for the same.

Hey @Siddhant-K-code 👋
I have raised a PR making the required changes. Please review it.
PR - #194
