### ISSUE TITLE
https://github.com/dipakkr/A-to-Z-Resources-for-Students

### ISSUE THREAD

**Issue by dipakkr** [gitpod-io/contribute.dev#26]
### Why is your project interesting/exciting to contribute to?

The project has more than 5k curated resources in a diverse category like coding resources, hackathons, events, meetups, conferences, podcast and much more. People can either read or contribute to help the community. 

### Does your project have an active community?
Yes, we do have a gitter channel where people share resources and know about each other.
https://gitter.im/a2z-resources/Lobby

### Does your project have basic newcomer onboarding docs? (e.g. CONTRIBUTING.md, good-first-issues...)
Yes, the project has a Contributing file and beginner's issue are tagged with relevant tags.

**Comment by jankeromnes** [comment]
It seems that this project was added last year. 🎉 

I'll close this issue then. 😊
