### ISSUE TITLE
https://github.com/docToolchain/aoc-2019

### ISSUE THREAD

**Issue by rdmueller** [gitpod-io/contribute.dev#37]
### Is your project's development setup fully automated? How to use it?

Just click on the "open in gitpod" button :-)

### Why is your project interesting/exciting to contribute to?

In this repository, we collect solutions for https://adventofcode.com - the perfect way to learn something new every day. The solutions are renderes as website on https://aoc-2019.netlify.com

### Does your project have an active community?

yes, we have now 24 conributers

### Does your project have basic newcomer onboarding docs? (e.g. CONTRIBUTING.md, good-first-issues...)

I think yes, take a look at https://aoc-2019.netlify.com/rules/

**Comment by nisarhassan12** [comment]
Thanks! :slightly_smiling_face: @rdmueller for the issue. Your project is now listed on https://contribute.dev :tada: 
![image](https://user-images.githubusercontent.com/46004116/70429675-e6577b00-1a9a-11ea-8df7-388531c15879.png)
