### ISSUE TITLE
Site does not have a custom 404 page.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/contribute.dev#45]
@ChristinFrohne Can you please give me a mockup so that i can make one.

**Comment by ChristinFrohne** [comment]
Sure 
<img width="635" alt="Bildschirmfoto 2020-01-17 um 10 08 33" src="https://user-images.githubusercontent.com/46345125/72599076-5adece80-3911-11ea-8699-90ae1aab8f85.png">

https://xd.adobe.com/view/3aa3599c-cbd6-4df6-53e3-4120a20f8f47-4c92/screen/d71b5395-a1a8-4d0e-a321-1bc51b6753a3/Final-5

[error404.svg.zip](https://github.com/gitpod-io/contribute.dev/files/4075905/error404.svg.zip)

**Comment by nisarhassan12** [comment]
@ChristinFrohne This looks nice but we don't have a Navigation here so I think it would make sense to have a link that goes back to the homepage :slightly_smiling_face: What do you say ?

**Comment by ChristinFrohne** [comment]
@nisarhassan12 nice catch! Yes, that makes totally sense. Please, add a `Back to Home` button underneath the text.
