### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/contribute.dev#5]
There are layout issues when changing the width.

1) the paper plane and it's stream are not in sync
2) the repository cards look bad in smaller widths (alignment issues)

**Comment by ChristinFrohne** [comment]
Some more comments 
- the arrow in the search box is not aligned
- I'm not a fan of the box animation. But the arrow and the navigation animation is great!
- "Just ‚open in Gitpod‘ and start coding." is semibold right? It differentiates too little from the rest. Can you try making it bold or extra bold?
- we should have more tweets. I can have a look at them 
- the logos from the sponsors should link to their website
- I updated the rocket path
[Path-rocket.svg.zip](https://github.com/gitpod-io/contribute.dev/files/3420792/Path-rocket.svg.zip)

**Comment by nisarhassan12** [comment]
@svenefftinge Thanks! a lot for the Feedback! I have fixed this issue.
