### ISSUE TITLE
Please add https://github.com/MovingBlocks/DestinationSol

### ISSUE THREAD

**Issue by Cervator** [gitpod-io/contribute.dev#76]
Adding the _smaller_ of our games as it was easier to get started with. Other one coming soon - it has the numbers for notability, even if DS on its own isn't quite there yet (180 stars/45 contributors DS, 2.8k stars/245 contributors [Terasology](https://github.com/MovingBlocks/Terasology))

### Is your project's development setup fully automated? How to use it?

Yep! Button added to our readme. Click it and execute `./gradlew run` when the workspace is ready. Play game.

### Why is your project interesting/exciting to contribute to?

Video game! Everybody loves video games. Especially when stuck inside ;-)

We focus heavily on making contributing _easy_ and fun, while teaching & learning together

### Does your project have an active community?

Yep! We also participate in various open source programs like Google Summer of Code, Google Code-In, Outreachy, etc.

### Does your project have basic newcomer onboarding docs? (e.g. CONTRIBUTING.md, good-first-issues...)

Yep and yep. https://github.com/MovingBlocks/DestinationSol/wiki - although again Terasology has the more extensive setup, which we'll add soon https://github.com/MovingBlocks/Terasology/wiki :-)

Side shout-out to @NicholasBatesNZ for the initial working setup for DS and @jankeromnes for the warm welcome 👏

**Comment by jankeromnes** [comment]
This is a really cool addition to contribute.dev -- many thanks! 🙏 

> Click it and execute `./gradlew run` when the workspace is ready. Play game.

I think now even the `./gradlew run` step is automated. 😇

> Video game! Everybody loves video games. Especially when stuck inside ;-)
> 
> We focus heavily on making contributing _easy_ and fun, while teaching & learning together

This is so true. And as previously mentioned, I agree that video games are one of the best ways to get into programming -- learning while also having fun is such a powerful combo. 💯

> We also participate in various open source programs like Google Summer of Code, Google Code-In, Outreachy, etc.

Wow, that's an impressive line-up, and Outreachy is amazing -- I didn't know you participated there as well. Kudos to you for doing all the hard work and building cool things for the community!
