### ISSUE TITLE
Please add https://github.com/MovingBlocks/Terasology

### ISSUE THREAD

**Issue by Cervator** [gitpod-io/contribute.dev#77]
See #76 - now our main game Terasology is ready as well!

1 FPS be damned, it runs! ;-) We'll iterate, that fixes everything.

https://github.com/MovingBlocks/Terasology

**Comment by jankeromnes** [comment]
> 1 FPS be damned, it runs! ;-) We'll iterate, that fixes everything.

100% agreed! It would be cool to reach a fluid UX in Gitpod's Virtual Desktop (ideally with sound).

In good conditions, I've seen noVNC become almost fluid enough to be able to watch a YouTube video (without sound though, by installing or building Firefox in the Virtual Desktop and then opening any YouTube video in it).
