### ISSUE TITLE
Improve page title

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/contribute.dev#81]
Currently, the title of https://contribute.dev is:

> Contribute.dev

<img width="623" alt="Screenshot 2020-04-08 at 18 38 09" src="https://user-images.githubusercontent.com/599268/78810071-220e3d00-79c8-11ea-98be-f68bf148151e.png">

We could try to find a better title, or at least add a few words to the title to hint at what this site is all about.

**Comment by nisarhassan12** [comment]
Thanks! @jankeromnes which one would make more sense? 

**Contribute.dev | Frictionless OSS Contributions with a single click**
or
**Contribute.dev | list of cool open source projects that you can contribute to with one click!**
