### ISSUE TITLE
yarn add-project is not working.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/contribute.dev#84]
I'm trying to add #83 via the `add-project` script.

![image](https://user-images.githubusercontent.com/46004116/80438599-fe327d00-891d-11ea-8592-6fe6512915f0.png)

**Comment by nisarhassan12** [comment]
I have added the project manually and the stars are not displaying: 
![image](https://user-images.githubusercontent.com/46004116/80439395-e0feae00-891f-11ea-92b6-53c25947dd4d.png)

**Comment by jankeromnes** [comment]
> I have added the project manually and the stars are not displaying:

This is likely a cache problem on shields.io (since this service receives many many requests, they need to heavily cache the most used badges -- so if you start using a new badge, it may be really slow to appear at first, but it should get better once it is properly cached by shields.io)

**Comment by nisarhassan12** [comment]
Many Thanks! :pray: @jankeromnes for the brief explanation.
